[project]
name = "pix2pix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "onnx>=1.22.0",
    "onnxconverter-common>=1.16.0",
    "onnxruntime>=1.29.0",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "tqdm>=4.70.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu130", marker = "sys_platform != 'darwin'" }]
torchvision = [{ index = "pytorch-cu130", marker = "sys_platform != 'darwin'" }]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
